.gitlab-registry-login: &docker-login
  docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

image: docker:latest

stages:
  - lint
  - build
  - debug
  - pre-test
  - test
  - post-test
  - publish

hadolint:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script: hadolint
            --ignore DL3007
            --ignore DL3008
            --ignore SC2016
            Dockerfile
build:
  stage: build
  script:
    - *docker-login
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}" . | tee docker-build-debug.out
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  artifacts:
    paths:
      - docker-build-debug.out
    when: on_failure
    expire_in: 30 mins

debug-failed-build:
  stage: debug
  script:
    - *docker-login
    - DEBUG_LAYER=$(grep '\-\-\-> [0-9a-z]' docker-build-debug.out |tail -1| cut -b 7-)
    - docker tag "$DEBUG_LAYER" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-failed"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-failed"
  when: on_failure
  dependencies:
    - build

start-target:
  stage: pre-test
  script:
    - docker network create "gitlab-ci-$CI_PIPELINE_ID"
    - docker run -d --name "target-$CI_PIPELINE_ID" --privileged --network "gitlab-ci-$CI_PIPELINE_ID" -v /sys/fs/cgroup:/sys/fs/cgroup:ro "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

test-ssh-port:
  stage: test
  script: docker run --rm --network "gitlab-ci-$CI_PIPELINE_ID" busybox:latest /bin/sh -c "echo exit | telnet target-$CI_PIPELINE_ID 22"

.test-aci-base-playbook:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  variables:
    PLAYBOOKDIR: '/ansibleci-base/examples/default'
  script: run-tests

.test-custom-playbook:
  stage: test
  image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"
  variables:
    PLAYBOOKDIR: "test"
  script: run-tests

stop-target:
  stage: post-test
  script:
    - docker rm -vf "target-$CI_PIPELINE_ID"
    - docker network remove "gitlab-ci-$CI_PIPELINE_ID"
  when: always

dockerhub:
  stage: publish
  script:
    - if [ "$CI_COMMIT_REF_SLUG" == "master" ]; then IMAGE_TAG="latest"; else IMAGE_TAG="$CI_COMMIT_REF_SLUG"; fi
    - IMAGE_NAME="${GITLAB_SECRET_DOCKER_USER}/${CI_PROJECT_NAME}:${IMAGE_TAG}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}" "$IMAGE_NAME"
    - docker login -u "$GITLAB_SECRET_DOCKER_USER" -p "$GITLAB_SECRET_DOCKER_PASSWORD"
    - docker push "$IMAGE_NAME"
